#!/usr/bin/env bash

_program()
{
	core_usesIn core temporaryFiles
	core_usesIn bishbosh validate client
	
	bishbosh()
	{
		bishbosh_client_plaintext_find
		
		local TMP_FOLDER
		core_temporaryFiles_newFolderToRemoveOnExit
		local bishbosh_temporaryFolderPath="$TMP_FOLDER"
		
		bishbosh_connection_makeClientConnection
	}
}

_program_name='bish-bosh'
_program_namespace='bishbosh'
_program_version='unversioned'
_program_package_or_build=''
_program_copyright='(c) 2014 Raphael Cohn'
_program_licence='MIT'
_program_written_by='Raphael Cohn'
_program_path="$([ "${_program_fattening_program_path+set}" = 'set' ] && printf '%s\n' "$_program_fattening_program_path" || ([ "${0%/*}" = "${0}" ] && printf '%s\n' '.' || printf '%s\n' "${0%/*}"))"
_program_libPath="${_program_path}/lib"
_program_etcPath="${_program_path}/etc"
_program_varPath="${_program_path}/var"
_program_entrypoint='bishbosh'

_program_commandLine_parseInitialise()
{
	_program_default_backends='ncat,nc6,nc,bash,socat,tcpclient'
	if core_variable_isSet bishbosh_backends; then
		_program_configurationSet_bishbosh_backends=0
	else
		_program_configurationSet_bishbosh_backends=1
	fi

	_program_default_server='localhost'
	if core_variable_isSet bishbosh_server; then
		_program_configurationSet_bishbosh_server=0
	else
		_program_configurationSet_bishbosh_server=1
	fi
	
	if core_variable_isSet bishbosh_port; then
		_program_configurationSet_bishbosh_port=0
	else
		_program_configurationSet_bishbosh_port=1
	fi

	_program_default_clientPath="${_program_varPath}"/lib/"$_program_name"/client
	if core_variable_isSet bishbosh_clientPath; then
		_program_configurationSet_bishbosh_clientPath=0
	else
		_program_configurationSet_bishbosh_clientPath=1
	fi
	
	_program_default_sessionPath="${_program_varPath}"/spool/"$_program_name"/session
	if core_variable_isSet bishbosh_sessionPath; then
		_program_configurationSet_bishbosh_sessionPath=0
	else
		_program_configurationSet_bishbosh_sessionPath=1
	fi
	
	_program_default_lockPath="${_program_varPath}"/run/"$_program_name"/lock
	if core_variable_isSet bishbosh_lockPath; then
		_program_configurationSet_bishbosh_lockPath=0
	else
		_program_configurationSet_bishbosh_lockPath=1
	fi

	if [ "$core_init_preferredShell" = 'zsh' ]; then
		_program_default_readLatency=0
	else
		_program_default_readLatency=1
	fi
	if core_variable_isSet bishbosh_readLatency; then
		_program_configurationSet_bishbosh_readLatency=0
	else
		_program_configurationSet_bishbosh_readLatency=1
	fi

	_program_default_lockLatency=1
	if core_variable_isSet bishbosh_lockLatency; then
		_program_configurationSet_bishbosh_lockLatency=0
	else
		_program_configurationSet_bishbosh_lockLatency=1
	fi
	
	if core_variable_isSet bishbosh_transport; then
		_program_configurationSet_bishbosh_transport=0
	else
		_program_configurationSet_bishbosh_transport=1
	fi
	
	if core_variable_isSet bishbosh_sourceAddress; then
		_program_configurationSet_bishbosh_sourceAddress=0
	else
		_program_configurationSet_bishbosh_sourceAddress=1
	fi
	
	if core_variable_isSet bishbosh_sourcePort; then
		_program_configurationSet_bishbosh_sourcePort=0
	else
		_program_configurationSet_bishbosh_sourcePort=1
	fi
	
	if core_variable_isSet bishbosh_proxyKind; then
		_program_configurationSet_bishbosh_proxyKind=1
	else
		_program_configurationSet_bishbosh_proxyKind=0
	fi
	
	if core_variable_isSet bishbosh_proxyServer; then
		_program_configurationSet_bishbosh_proxyServer=1
	else
		_program_configurationSet_bishbosh_proxyServer=0
	fi
	
	if core_variable_isSet bishbosh_proxyPort; then
		_program_configurationSet_bishbosh_proxyPort=1
	else
		_program_configurationSet_bishbosh_proxyPort=0
	fi
	
	if core_variable_isSet bishbosh_proxyUsername; then
		_program_configurationSet_bishbosh_proxyUsername=1
	else
		_program_configurationSet_bishbosh_proxyUsername=0
	fi
	
	if core_variable_isSet bishbosh_proxyPassword; then
		_program_configurationSet_bishbosh_proxyPassword=1
	else
		_program_configurationSet_bishbosh_proxyPassword=0
	fi
}

_program_commandLine_helpMessage()
{
	_program_commandLine_helpMessage_usage="[OPTION]... -- [SCRIPTLETS]..."
	_program_commandLine_helpMessage_description="Connects to a MQTT server and runs SCRIPTLETS.
May be used as a command interpreter in scripts starting #!/usr/bin/env ${_program_name}
if on the PATH."
	_program_commandLine_helpMessage_options="
  -s, --server HOST         Server hostname, HOST, Unix domain socket path,
                            IPv4 or IPv6 address.
                            Unix domain socket paths must contain a '/' (ie
                            they can not be in the present working directory).
  -p, --port PORT           Server PORT. Ignored for Unix domain sockets.
                            Use 'BACKEND' to let the backend choose.
                            Defaults to 1883 or 8883 depending on backend
  -i, --client-id ID        Specifies the client id to use. Any SCRITPLETS
                            found at --clients-path PATH/ID will then be
                            sourced. SCRIPTLETS control how a connection is
                            managed. ${_program_name} does not generate
                            random IDs, although a SCRIPTLET or configuration
                            is entitled to.
  -b, --backends A,B,...    Backend types A,B,... to talk to MQTT server.
                            Ordered in preference order. First found used.
                            Comma separated.
                            Defaults to '${_program_default_backends}'.
  -c, --client-path PATH    PATH to folder containing client scriptlets.
                            Defaults to '${_program_default_clientPath}'.
  -t, --session-path PATH   PATH to folder containing session data for
                            Clean Session = 0 clients.
                            Defaults to '${_program_default_sessionPath}'.
  -l, --lock-path PATH      PATH to a parent folder for locking with a
                            Mutex; ensures only one copy runs at a time.
                            Defaults to '${_program_default_lockPath}'.
      --read-latency MSECS  Maximum time to block for when reading in
                            MSECS milliseconds between 0 and 1000
                            inclusive. 0 has different meaning in
                            'zsh' as opposed to 'bash'.
                            Defaults to '${_program_default_readLatency}'.
                            Default varies by detected shell.
      --lock-latency MSECS  Maximum time to sleep for when trying to acquire a
                            lock in MSECS milliseconds between 0 and 1000
                            inclusive. Defaults to '${_program_default_lockLatency}'.
      --transport TRANSPT   TRANSPT of inet, inet4, inet6 or unix.
                            Defaults to 'inet'
      --source-address S    Bind to network interface with address S.
                            Should not normally be needed.
                            Turn off with ''.
                            Off by default.
                            Does not work with transport 'unix'.
      --source-port PORT    Send packets from port PORT.
                            Should not normally be needed.
                            Turn off with ''.
                            Off by default.
                            Does not work with transport 'unix'.
      --proxy-kind KIND     Use a particular KIND of proxy.
                            KIND is 'SOCKS4','SOCKS5','HTTP' or 'none'.
                            Turn off with 'none'.
                            Off by default.
                            Does not work with transport 'unix'.
                            Not all backends support this option.
      --proxy-server HOST   Connect to a proxy on a given HOST.
                            Turn off with ''.
                            Off by default.
                            Does not work with transport 'unix'.
      --proxy-port PORT     Connect to a proxy on a given PORT.
                            Turn off with ''.
                            Off by default, but defaults to 1080
                            for SOCKS4 / SOCKS5 and 3128 for HTTP.
                            Does not work with transport 'unix'.
      --proxy-username UN   Connect to a proxy using username UN.
                            Turn off with ''.
                            Off by default.
                            Does not work with transport 'unix'.
                            Insecure - use configuration instead.
                            Not all proxies support this option.
      --proxy-password PWD  Connect to a proxy using password PWD.
                            Turn off with ''.
                            Off by default.
                            Does not work with transport 'unix'.
                            Insecure - use configuration instead.
                            Not all proxies support this option."
    _program_commandLine_helpMessage_optionsSpacing='   '
	_program_commandLine_helpMessage_configurationKeys="
  bishbosh_backends       Equivalent to --backends
  bishbosh_server         Equivalent to --server
  bishbosh_port           Equivalent to --port
  bishbosh_clientPath     Equivalent to --clients-path
  bishbosh_sessionPath    Equivalent to --session-path
  bishbosh_clientId       Equivalent to --client-id
  bishbosh_readLatency    Equivalent to --read-latency
  bishbosh_transport      Equivalent to --transport
  bishbosh_sourceAddress  Equivalent to --source-address
  bishbosh_sourcePort     Equivalent to --source-port
  bishbosh_proxyKind      Equivalent to --proxy-kind
  bishbosh_proxyServer    Equivalent to --proxy-server
  bishbosh_proxyPort      Equivalent to --proxy-port
  bishbosh_proxyUsername  Equivalent to --proxy-username
  bishbosh_proxyPassword  Equivalent to --proxy-password
  
These may also be set in the SCRIPTLETS.

The following values may be used in SCRIPTLETS to manage a connection:-
  bishbosh_connection_write_CONNECT_cleanSession  Mandatory Boolean
  bishbosh_connection_write_CONNECT_willTopic     Optional  String
  bishbosh_connection_write_CONNECT_willMessage   Optional  Binary*
  bishbosh_connection_write_CONNECT_willQos       Optional  0 - 2
  bishbosh_connection_write_CONNECT_willRetain    Optional
  bishbosh_connection_write_CONNECT_keepAlive     Mandatory 0 - 65535
  bishbosh_connection_write_CONNECT_username      Optional  String
  bishbosh_connection_write_CONNECT_password      Optional  Binary*

  * ASCII NUL (0x00) is not supported.

The following values may be used to override client-id based configuration:-
  bishbosh_connection_clientServersPath
  bishbosh_connection_clientServersPortsPath
  bishbosh_connection_clientServersPortsClientIdsPath

  XXX Under review XXX
  bishbosh_connection_nextPacketIdentifier
  
The following handlers may be specified as functions in SCRIPTLETS, with
the globals specified:-
  bishbosh_connection_handler_CONNACK()
  bishbosh_connection_handler_SUBACK()
  bishbosh_connection_handler_UNSUBACK()
  bishbosh_connection_handler_PUBLISH()
  bishbosh_connection_handler_PUBACK()
  bishbosh_connection_handler_PUBREC()
  bishbosh_connection_handler_PUBREL()
  bishbosh_connection_handler_PUBCOMP()
  bishbosh_connection_handler_PINGRESP()
"
	_program_commandLine_helpMessage_examples="
  ${_program_name} --server localhost --backends ncMacOSX,bash --client-id 12 -- /path/to/connection-details.scriptlet
"
}

_program_commandLine_optionExists()
{
	case "$optionName" in
		
		s|server)
			echo 'yes-argumented'
		;;
		
		p|port)
			echo 'yes-argumented'
		;;
		
		i|client-id)
			echo 'yes-argumented'
		;;
		
		b|backends)
			echo 'yes-argumented'
		;;
		
		c|clients-path)
			echo 'yes-argumented'
		;;
		
		t|session-path)
			echo 'yes-argumented'
		;;
		
		l|lock-path)
			echo 'yes-argumented'
		;;
		
		read-latency)
			echo 'yes-argumented'
		;;
		
		lock-latency)
			echo 'yes-argumented'
		;;
		
		transport)
			echo 'yes-argumented'
		;;
		
		source-address)
			echo 'yes-argumented'
		;;
		
		source-port)
			echo 'yes-argumented'
		;;
		
		proxy-kind)
			echo 'yes-argumented'
		;;
		
		proxy-server)
			echo 'yes-argumented'
		;;
		
		proxy-port)
			echo 'yes-argumented'
		;;
		
		proxy-username)
			echo 'yes-argumented'
		;;
		
		proxy-password)
			echo 'yes-argumented'
		;;
		
		*)
			echo 'no'
		;;
		
	esac
}

_program_commandLine_processOptionWithoutArgument()
{
	:
}

_program_commandLine_processOptionWithArgument()
{
	case "$optionName" in
		
		s|server)
			bishbosh_validate_address $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			bishbosh_server="$optionValue"
		;;
		
		p|port)
			core_validate_nonDynamicPort $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			bishbosh_port="$optionValue"
		;;
		
		i|client-id)
			bishbosh_clientId="$optionValue"
		;;
		
		b|backends)
			bishbosh_validate_backends $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			bishbosh_backends="$optionValue"
		;;
		
		c|clients-path)
			core_validate_folderPathReadableAndSearchableAndWritable $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			bishbosh_clientPath="$optionValue"
		;;
		
		t|session-path)
			core_validate_folderPathReadableAndSearchableAndWritable $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			bishbosh_sessionPath="$optionValue"
		;;
		
		l|lock-path)
			core_validate_folderPathReadableAndSearchableAndWritable $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			bishbosh_lockPath="$optionValue"
		;;
		
		read-latency)
			bishbosh_validate_latency $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			bishbosh_readLatency="$optionValue"
		;;
		
		lock-latency)
			bishbosh_validate_latency $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			bishbosh_lockLatency="$optionValue"
		;;
		
		transport)
			bishbosh_validate_transport $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			bishbosh_transport="$optionValue"
		;;
		
		source-address)
			bishbosh_validate_address $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			bishbosh_sourceAddress="$optionValue"
		;;
		
		source-port)
			core_validate_nonDynamicPort $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			bishbosh_sourcePort="$optionValue"
		;;
		
		proxy-kind)
			bishbosh_validate_proxyKind $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			bishbosh_proxyKind="$optionValue"
			_program_configurationSet_bishbosh_proxyKind=0
		;;
		
		proxy-server)
			bishbosh_validate_address $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			bishbosh_proxyServer="$optionValue"
			_program_configurationSet_bishbosh_proxyServer=0
		;;
		
		proxy-port)
			core_validate_nonDynamicPort $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			bishbosh_proxyPort="$optionValue"
			_program_configurationSet_bishbosh_proxyPort=0
		;;
		
		proxy-username)
			core_message WARN "Specifying the option '--proxy-username' on the command line is insecure"
			bishbosh_proxyUsername="$optionValue"
			_program_configurationSet_bishbosh_proxyUsername=0
		;;
		
		proxy-password)
			core_message WARN "Specifying the option '--proxy-password' on the command line is insecure"
			bishbosh_proxyPassword="$optionValue"
			_program_configurationSet_bishbosh_proxyPassword=0
		;;
		
	esac
}

_program_commandLine_handleNonOptions()
{
	local scriptletFilePath
	local suitableForSourceBuiltInFilePath
	for scriptletFilePath in "$@"
	do
		suitableForSourceBuiltInFilePath=$(core_compatibility_dirname "$scriptletFilePath")/"$(core_compatibility_basename "$scriptletFilePath")"
		. "$suitableForSourceBuiltInFilePath" || core_exitError "Could not source SCRIPTLET '$scriptletFilePath'"
	done
}

_program_commandLine_validateTransportSetting()
{
	local variableName="$1"
	local optionName="$2"
	local description="$3"
	local configurationSet=$4
	
	local code
	local category
	local name
	if core_variable_isSet "$variableName"; then
		local core_variable_indirectValue_result
		core_variable_indirectValue "$variableName"
		
		if [ $_program_configurationSet_bishbosh_transport -eq 1 ]; then
			if [ $configurationSet -eq 1 ]; then
				code=$core_commandLine_exitCode_CONFIG
				category='configuration setting'
				name="$variableName"
			else
				code=$core_commandLine_exitCode_USAGE
				category='option'
				name='--source-address'
			fi
			core_exitError $code "The $category '$name' specified a $description ('$core_variable_indirectValue_result') but the transport ($categoryTransport '$nameTransport') is '$bishbosh_transport'"
		fi
	fi
}

_program_commandLine_validateProxySetting()
{
	local noneOrUnspecified="$1"
	local variableName="$2"
	local optionName="$3"
	local description="$4"
	local configurationSet=$5
	
	local code
	local category
	local name
	local message
	
	if core_variable_isSet "$variableName"; then
		local core_variable_indirectValue_result
		core_variable_indirectValue "$variableName"
		
		if [ $configurationSet -eq 1 ]; then
			code=$core_commandLine_exitCode_CONFIG
			category='configuration setting'
			name="$variableName"
		else
			code=$core_commandLine_exitCode_USAGE
			category='option'
			name="$optionName"
		fi
		
		if [ $_program_configurationSet_bishbosh_proxyKind -eq 1 ]; then
			categoryProxyKind='configuration setting'
			nameProxyKind='bishbosh_proxyKind'
		else
			categoryProxyKind='option'
			nameProxyKind='--proxy-kind'
		fi
		
		message="The $category '$name' specifies a $description ('$core_variable_indirectValue_result') but the proxy kind ($categoryProxyKind '$nameProxyKind') is $noneOrUnspecified"
		if [ "$noneOrUnspecified" = "unspecified" ]; then
			core_exitError $code "$message"
		else
			core_message WARN "$message"
		fi
	fi
}

_program_commandLine_validate()
{
	local categoryProxyKind
	local nameProxyKind
	if [ $_program_configurationSet_bishbosh_proxyKind -eq 1 ]; then
		categoryProxyKind='configuration setting'
		nameProxyKind='bishbosh_proxyKind'
	else
		categoryProxyKind='option'
		nameProxyKind='--proxy-kind'
	fi
	
	local codeTransport
	local categoryTransport
	local nameTransport
	if [ $_program_configurationSet_bishbosh_transport -eq 1 ]; then
		codeTransport=$core_commandLine_exitCode_CONFIG
		categoryTransport='configuration setting'
		nameTransport='bishbosh_transport'
	else
		codeTransport=$core_commandLine_exitCode_USAGE
		categoryTransport='option'
		nameTransport='--transport'
	fi
	
	local codeServer
	local categoryServer
	local nameServer
	if [ $_program_configurationSet_bishbosh_server -eq 1 ]; then
		codeServer=$core_commandLine_exitCode_CONFIG
		categoryServer='configuration setting'
		nameServer='bishbosh_server'
	else
		codeServer=$core_commandLine_exitCode_USAGE
		categoryServer='option'
		nameServer='--server'
	fi
	
	if core_variable_isUnset bishbosh_backends; then
		bishbosh_backends="$_program_default_backends"
	else
		bishbosh_validate_backends $core_commandLine_exitCode_CONFIG 'configuration setting' 'bishbosh_backends' "$bishbosh_backends"
	fi
	
	if core_variable_isUnset bishbosh_server; then
		bishbosh_server="$_program_default_server"
	else
		bishbosh_validate_address $core_commandLine_exitCode_CONFIG 'configuration setting' "bishbosh_server" "$bishbosh_server"
	fi
	
	if core_variable_isUnset bishbosh_clientPath; then
		bishbosh_clientPath="$_program_default_clientPath"
		core_validate_folderPathReadableAndSearchableAndWritable $core_commandLine_exitCode_CONFIG 'defaulted value for' '--client-path' "$bishbosh_clientPath"
	else
		core_validate_folderPathReadableAndSearchable $core_commandLine_exitCode_CONFIG 'configuration setting' 'bishbosh_clientPath' "$bishbosh_clientPath"
	fi
	
	if core_variable_isUnset bishbosh_sessionPath; then
		bishbosh_sessionPath="$_program_default_sessionPath"
		core_validate_folderPathReadableAndSearchableAndWritable $core_commandLine_exitCode_CONFIG 'defaulted value for' '--session-path' "$bishbosh_sessionPath"
	else
		core_validate_folderPathReadableAndSearchable $core_commandLine_exitCode_CONFIG 'configuration setting' 'bishbosh_sessionPath' "$bishbosh_sessionPath"
	fi
	
	if core_variable_isUnset bishbosh_lockPath; then
		bishbosh_lockPath="$_program_default_lockPath"
		core_validate_folderPathReadableAndSearchableAndWritable $core_commandLine_exitCode_CONFIG 'defaulted value for' '--lock-path' "$bishbosh_lockPath"
	else
		core_validate_folderPathReadableAndSearchable $core_commandLine_exitCode_CONFIG 'configuration setting' 'bishbosh_lockPath' "$bishbosh_lockPath"
	fi
	
	if core_variable_isUnset bishbosh_clientId; then
		core_exitError $core_commandLine_exitCode_CONFIG "The option -i,--client-id or configuration setting bishbosh_clientId isn't set, either in configuration or SCRIPTLETS"
	fi
	
	if core_variable_isUnset bishbosh_readLatency; then
		bishbosh_readLatency="$_program_default_readLatency"
	else
		bishbosh_validate_latency $core_commandLine_exitCode_CONFIG 'configuration setting' 'bishbosh_readLatency' "$bishbosh_readLatency"
	fi
	if [ $bishbosh_readLatency -lt 1 ]; then
		bishbosh_readLatency_inFractionalSeconds=0
	elif [ $bishbosh_readLatency -lt 10 ]; then
		bishbosh_readLatency_inFractionalSeconds=0.00${bishbosh_readLatency}
	elif [ $bishbosh_readLatency -lt 100 ]; then
		bishbosh_readLatency_inFractionalSeconds=0.0${bishbosh_readLatency}
	elif [ $bishbosh_readLatency -lt 1000 ]; then
		bishbosh_readLatency_inFractionalSeconds=0.${bishbosh_readLatency}
	else
		bishbosh_readLatency_inFractionalSeconds=1
	fi
	
	if core_variable_isUnset bishbosh_lockLatency; then
		bishbosh_lockLatency="$_program_default_lockLatency"
	else
		bishbosh_validate_latency $core_commandLine_exitCode_CONFIG 'configuration setting' 'bishbosh_lockLatency' "$bishbosh_lockLatency"
	fi
	if [ $bishbosh_lockLatency -lt 1 ]; then
		bishbosh_lockLatency_inFractionalSeconds=0
	elif [ $bishbosh_lockLatency -lt 10 ]; then
		bishbosh_lockLatency_inFractionalSeconds=0.00${bishbosh_lockLatency}
	elif [ $bishbosh_lockLatency -lt 100 ]; then
		bishbosh_lockLatency_inFractionalSeconds=0.0${bishbosh_lockLatency}
	elif [ $bishbosh_lockLatency -lt 1000 ]; then
		bishbosh_lockLatency_inFractionalSeconds=0.${bishbosh_lockLatency}
	else
		bishbosh_lockLatency_inFractionalSeconds=1
	fi
	
	if core_variable_isUnset bishbosh_transport; then
		bishbosh_transport=inet
	else
		bishbosh_validate_transport $core_commandLine_exitCode_CONFIG 'configuration setting' 'bishbosh_transport' "$bishbosh_transport"
		if [ "$bishbosh_transport" = unix ]; then
			if [ ! core_validate_socketPathReadableAndWritable "$bishbosh_server" ]; then
				core_exitError $codeServer "When $categoryTransport '$nameTransport' is 'unix' the $categoryServer '$nameServer' must be a path to a readable, writable domain socket ('$bishbosh_socket' is not)"
			fi
			_program_commandLine_validateTransportSetting bishbosh_sourceAddress '--source-address' 'source address' $_program_configurationSet_bishbosh_sourceAddress
			_program_commandLine_validateTransportSetting bishbosh_sourcePort '--source-port' 'source port' $_program_configurationSet_bishbosh_sourcePort
			_program_commandLine_validateTransportSetting bishbosh_port '-p/--port' 'destination port' $_program_configurationSet_bishbosh_port
		fi
	fi
	
	if core_variable_isSet bishbosh_proxyKind; then
		bishbosh_validate_proxyKind $core_commandLine_exitCode_CONFIG 'configuration setting' 'bishbosh_proxyKind' "$bishbosh_proxyKind"
		
		if [ "$bishbosh_proxyKind" = 'none' ]; then
			_program_commandLine_validateProxySetting "'none'" bishbosh_proxyServer '--proxy-server' 'proxy server' $_program_configurationSet_bishbosh_proxyServer
			_program_commandLine_validateProxySetting "'none'" bishbosh_proxyPort '--proxy-port' 'proxy port' $_program_configurationSet_bishbosh_proxyPort
			_program_commandLine_validateProxySetting "'none'" bishbosh_proxyUsername '--proxy-username' 'proxy username' $_program_configurationSet_bishbosh_proxyUsername
			_program_commandLine_validateProxySetting "'none'" bishbosh_proxyPassword '--proxy-password' 'proxy password' $_program_configurationSet_bishbosh_proxyPassword
		else
			_program_commandLine_validateTransportSetting bishbosh_proxyKind '--proxy-kind' 'proxy kind' $_program_configurationSet_bishbosh_proxyKind
			if core_variable_isUnset bishbosh_proxyServer; then
				core_commandLine_exitBadCommandLine "The proxy kind ($categoryProxyKind '$nameProxyKind') is '$bishbosh_proxyKind' but the option '--proxy-server' is unspecified"
			fi
			if core_variable_isUnset bishbosh_proxyPort; then
				case "$bishbosh_proxyKind" in
					SOCKS4|SOCKS5)
						bishbosh_proxyPort=1080
					;;
					
					HTTP)
						bishbosh_proxyPort=3128
					;;
				esac
			else
				core_validate_nonDynamicPort $core_commandLine_exitCode_USAGE 'configuration setting' 'bishbosh_proxyPort' "$bishbosh_proxyPort"
			fi
		fi
	else
		_program_commandLine_validateProxySetting 'unspecified' bishbosh_proxyServer '--proxy-server' 'proxy server' $_program_configurationSet_bishbosh_proxyServer
		_program_commandLine_validateProxySetting 'unspecified' bishbosh_proxyPort '--proxy-port' 'proxy port' $_program_configurationSet_bishbosh_proxyPort
		_program_commandLine_validateProxySetting 'unspecified' bishbosh_proxyUsername '--proxy-username' 'proxy username' $_program_configurationSet_bishbosh_proxyUsername
		_program_commandLine_validateProxySetting 'unspecified' bishbosh_proxyPassword '--proxy-password' 'proxy password' $_program_configurationSet_bishbosh_proxyPassword
		bishbosh_proxyKind='none'
	fi
}

# Assumes pwd, and so requires this code to be running from this folder
. "$_program_libPath"/shellfire/core/init.functions "$@"
